### ISSUE TITLE
希望可以增加对GesturePassword尺寸的控制。

### ISSUE THREAD

**Issue by xia-weiyang** [zhangruiyu/flutter_gesture_password#1]
谢谢。

**Comment by zhangruiyu** [comment]
什么尺寸 哪里的大小啊

**Comment by xia-weiyang** [comment]
GesturePassword 这个Widget，我外边套了SizeBox等都没作用，它的宽度永远是占满整个屏幕宽度的，就是这个的大小 
![image](https://user-images.githubusercontent.com/11485324/45140694-2f5cb780-b1e6-11e8-96b1-1978e94d9a84.png)

**Comment by zhangruiyu** [comment]
添加了

**Comment by xia-weiyang** [comment]
👍，这效率，厉害了
